
import DownloadBanner from '@/app/components/widgets/banners/DownloadBanner'
import EmptyBanner from '@/app/components/widgets/banners/EmptyBanner'
import ErrorBanner from '@/app/components/widgets/banners/ErrorBanner'
import GreetingBanner from '@/app/components/widgets/banners/GreetingBanner'
import MutualFriendsBanner from '@/app/components/widgets/banners/MutualFriendBanner'
import NotificationsBanner from '@/app/components/widgets/banners/NotificationBanner'
import GreetingBanner2 from '@/app/components/widgets/banners/WelcomeBanner'
import BreadcrumbComp from '../../layout/shared/breadcrumb/BreadcrumbComp'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Banners Widgets',
  description: 'Generated by create next app',
}

const BCrumb = [
  {
    to: '/',
    title: 'Home',
  },
  {
    title: 'Banners',
  },
]

const Banners = () => {
  return (
    <>
      <BreadcrumbComp title='Banners' items={BCrumb} />
      <div className='grid grid-cols-12 gap-6'>
        <div className='col-span-12 scroll-mt-28' id='greetingbanner'>
          <GreetingBanner />
        </div>
        <div className='col-span-12 scroll-mt-28' id='downloadbanner'>
          <DownloadBanner />
        </div>
        <div className='col-span-12 scroll-mt-28' id='emptybanner'>
          <EmptyBanner />
        </div>
        <div className='col-span-12 scroll-mt-28' id='errorbanner'>
          <ErrorBanner />
        </div>
        <div className='col-span-12 scroll-mt-28' id='mutualfriendsbanner'>
          <MutualFriendsBanner />
        </div>
        <div className='col-span-12 scroll-mt-28' id='notificationsbanner'>
          <NotificationsBanner />
        </div>
        <div className='col-span-12 scroll-mt-28' id='greetingbanner2'>
          <GreetingBanner2 />
        </div>
      </div>
    </>
  )
}

export default Banners
