
import BreadcrumbComp from '../../layout/shared/breadcrumb/BreadcrumbComp'
import CurrentYear from '@/app/components/widgets/charts/CurrentYear'
import CustomersChart from '@/app/components/widgets/charts/Customers'
import RevenueChart from '@/app/components/widgets/charts/EarnedChart'
import ExpenseChart from '@/app/components/widgets/charts/ExpenseChart'
import FollowersChart from '@/app/components/widgets/charts/FollowersChart'
import IncomeChart from '@/app/components/widgets/charts/IncomeChart'
import MonthlyEarning from '@/app/components/widgets/charts/MonthlyEarning'
import VisitChart from '@/app/components/widgets/charts/MostVisited'
import ImpressionsChart from '@/app/components/widgets/charts/PageImpression'
import ProjectsChart from '@/app/components/widgets/charts/Projects'
import RevenueUpdatesChart from '@/app/components/widgets/charts/RevenueUpdates'
import SalesOverviewChart from '@/app/components/widgets/charts/SalesOverview'
import TotalEarningsChart from '@/app/components/widgets/charts/TotalEarnigs'
import Views from '@/app/components/widgets/charts/ViewsChart'
import WeeklyStatsChart from '@/app/components/widgets/charts/WeeklyStats'
import YearlyBreakupChart from '@/app/components/widgets/charts/YearlyBreakup'
import YearlySalesChart from '@/app/components/widgets/charts/YearlySales'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Chart Widgets',
  description: 'Generated by create next app',
}

const BCrumb = [
  {
    to: '/',
    title: 'Home',
  },
  {
    title: 'Charts',
  },
]

const Charts = () => {
  return (
    <>
      <BreadcrumbComp title='Charts' items={BCrumb} />
      <div className='grid grid-cols-12 gap-6'>
        <div className='col-span-12 scroll-mt-28' id='revenueupdateschart'>
          <RevenueUpdatesChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='yarlybreakupchart'>
          <YearlyBreakupChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='monthlyearning'>
          <MonthlyEarning />
        </div>
        <div className='col-span-12 scroll-mt-28' id='yearlysaleschart'>
          <YearlySalesChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='currentyear'>
          <CurrentYear />
        </div>
        <div className='col-span-12 scroll-mt-28' id='weeklystatschart'>
          <WeeklyStatsChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='expancechart'>
          <ExpenseChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='customerschart'>
          <CustomersChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='revenuechart'>
          <RevenueChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='followerchart'>
          <FollowersChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='incomechart'>
          <IncomeChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='visitchart'>
          <VisitChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='impressionschart'>
          <ImpressionsChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='projectschart'>
          <ProjectsChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='salesoverviewchart'>
          <SalesOverviewChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='totalearningschart'>
          <TotalEarningsChart />
        </div>
        <div className='col-span-12 scroll-mt-28' id='viewschart'>
          <Views />
        </div>
      </div>
    </>
  )
}

export default Charts
