import React from 'react'
import BreadcrumbComp from '../../layout/shared/breadcrumb/BreadcrumbComp'
import BlogCards from '@/app/components/widgets/cards/BlogCards'
import ProductsCards from '@/app/components/widgets/cards/ProductsCards'
import MusicCards from '@/app/components/widgets/cards/MusicCards'
import ProfileCards from '@/app/components/widgets/cards/ProfileCards'
import UserCards from '@/app/components/widgets/cards/UserCards'
import SocialCards from '@/app/components/widgets/cards/SocialCards'
import SettingsCard from '@/app/components/widgets/cards/SettingsCard'
import GiftCards from '@/app/components/widgets/cards/GiftCards'
import PaymentGateway from '@/app/components/widgets/cards/PaymentGatways'
import UpcommingActCard from '@/app/components/widgets/cards/UpcommingActivitiesCard'
import RecentTransactionCard from '@/app/components/widgets/cards/RecentTransactionCard'
import type { Metadata } from 'next'
import TopCards from '@/app/components/widgets/cards/TopCards'
import BestSellingProductCard from '@/app/components/widgets/cards/BestSellingProduct'
import RecentComments from '@/app/components/widgets/cards/RecentCommentsCard'
import TaskList from '@/app/components/widgets/cards/TaskList'
import RecentMessages from '@/app/components/widgets/cards/RecentMessages'
import UserInfoCard from '@/app/components/widgets/cards/UserInfoCard'
import SocialCard from '@/app/components/widgets/cards/SocialCard'
import ReviewCards from '@/app/components/widgets/cards/ReviewCards'
import FeedCard from '@/app/components/widgets/cards/FeedCard'
import UserProfileCard from '@/app/components/widgets/cards/UserProfileCard'
import PollOfWeek from '@/app/components/widgets/cards/PollOfWeekCard'
import PollResult from '@/app/components/widgets/cards/PollResultCard'
import SocialPostCard from '@/app/components/widgets/cards/SocialPostCard'

export const metadata: Metadata = {
  title: 'Card Widgets',
  description: 'Generated by create next app',
}

const BCrumb = [
  {
    to: '/',
    title: 'Home',
  },
  {
    title: 'Cards',
  },
]

const CardWidgets = () => {
  return (
    <>
      <BreadcrumbComp title='Cards' items={BCrumb} />
      <div className='grid grid-cols-12 gap-6'>
        <div className='col-span-12 scroll-mt-28' id='topCards'>
          <TopCards />
        </div>
        <div className='col-span-12 scroll-mt-28' id='bestsellingproduct'>
          <BestSellingProductCard />
        </div>
        <div className='col-span-12 scroll-mt-28' id='paymentgateway'>
          <PaymentGateway />
        </div>
        <div className='col-span-12 scroll-mt-28' id='blogcards'>
          <BlogCards />
        </div>
        <div className='col-span-12 scroll-mt-28' id='productscards'>
          <ProductsCards />
        </div>
        <div className='col-span-12 scroll-mt-28' id='musiccards'>
          <MusicCards />
        </div>
        <div className='col-span-12 scroll-mt-28' id='profilecards'>
          <ProfileCards />
        </div>
        <div className='col-span-12 scroll-mt-28' id='usercards'>
          <UserCards />
        </div>
        <div className='col-span-12 scroll-mt-28' id='socialcards'>
          <SocialCards />
        </div>
        <div className='col-span-12 scroll-mt-28' id='settingscard'>
          <SettingsCard />
        </div>
        <div className='col-span-12 scroll-mt-28' id='giftcards'>
          <GiftCards />
        </div>
        <div className='col-span-12 scroll-mt-28' id='upcommingactcard'>
          <UpcommingActCard />
        </div>
        <div className='col-span-12 scroll-mt-28' id='recenttransactioncard'>
          <RecentTransactionCard />
        </div>
        <div className='col-span-12 scroll-mt-28' id='recentcommentcard'>
          <RecentComments />
        </div>
        <div className='col-span-12 scroll-mt-28' id='tasklist'>
          <TaskList />
        </div>
        <div className='col-span-12 scroll-mt-28' id='recentmessages'>
          <RecentMessages />
        </div>
        <div className='col-span-12 scroll-mt-28' id='userinfocard'>
          <UserInfoCard />
        </div>
        <div className='col-span-12 scroll-mt-28' id='socialcard'>
          <SocialCard />
        </div>
        <div className='col-span-12 scroll-mt-28' id='reviewcard'>
          <ReviewCards />
        </div>
        <div className='col-span-12 scroll-mt-28' id='feedcard'>
          <FeedCard />
        </div>
        <div className='col-span-12 scroll-mt-28' id='userprofilecard'>
          <UserProfileCard />
        </div>
        <div className='col-span-12 scroll-mt-28' id='userprofilecard'>
          <PollOfWeek />
        </div>
        <div className='col-span-12 scroll-mt-28' id='resultofpoll'>
          <PollResult />
        </div>
        <div className='col-span-12 scroll-mt-28' id='socialpostcard'>
          <SocialPostCard />
        </div>
      </div>
    </>
  )
}

export default CardWidgets
