import React from "react";
import BreadcrumbComp from "../../../layout/shared/breadcrumb/BreadcrumbComp";
import ApexLineChart from "@/app/components/charts/ApexCharts/ApexLineChart";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Line Chart",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Line",
  },
];
const LineChart = () => {
  return (
    <>
      <BreadcrumbComp title="Chart Apex Line" items={BCrumb} />
      <ApexLineChart />
    </>
  );
};

export default LineChart;
